name: alphabet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  assets_audio_player : ^1.4.0+1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/twitter.png
     - assets/logo.png
     - assets/A1.png
     - assets/B1.png
     - assets/C1.png
     - assets/D1.png
     - assets/E1.png
     - assets/F1.png
     - assets/G1.png
     - assets/H1.png
     - assets/I1.png
     - assets/J1.png
     - assets/K1.png
     - assets/L1.png
     - assets/M1.png
     - assets/N1.png
     - assets/O1.png
     - assets/P1.png
     - assets/Q1.png
     - assets/R1.png
     - assets/S1.png
     - assets/T1.png
     - assets/U1.png
     - assets/V1.png
     - assets/W1.png
     - assets/X1.png
     - assets/Y1.png
     - assets/Z1.png
     - assets/A2.png
     - assets/B2.png
     - assets/C2.png
     - assets/D2.png
     - assets/E2.png
     - assets/F2.png
     - assets/G2.png
     - assets/H2.png
     - assets/I2.png
     - assets/J2.png
     - assets/K2.png
     - assets/L2.png
     - assets/M2.png
     - assets/N2.png
     - assets/O2.png
     - assets/P2.png
     - assets/Q2.png
     - assets/R2.png
     - assets/S2.png
     - assets/T2.png
     - assets/U2.png
     - assets/V2.png
     - assets/W2.png
     - assets/X2.png
     - assets/Y2.png
     - assets/Z2.png
     - assets/sound.mp3
     - assets/0.png
     - assets/1.png
     - assets/2.png
     - assets/3.png
     - assets/4.png
     - assets/5.png
     - assets/6.png
     - assets/7.png
     - assets/8.png
     - assets/9.png
     - assets/0a.png
     - assets/1a.png
     - assets/2a.png
     - assets/3a.png
     - assets/4a.png
     - assets/5a.png
     - assets/6a.png
     - assets/7a.png
     - assets/8a.png
     - assets/9a.png



  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
